### ISSUE TITLE
Data preparation for Link Prediction in Multi-relations Graph 

### ISSUE THREAD

**Issue by elbasir** [pyg-team/pytorch_geometric#1222]
Hi,
I am new to the concept of graphs in deep learning. Assume that I have three graphs as following:
1- Movie genres graph
2- Connected users graph
3- Connected cities by country graph

I realize the RGCN is the way to use for link prediction to predict for example if a user in a particular city would like to watch a movie from the movie-genres graph. The graph should be G =(V, E, R) where V is the node set, E is the edge and R is the relation. I am confused on how the data which are three graphs should be prepared to be passed to RGCN for link prediction.

Another question, any GAE implementation for link prediction?

Thanks,

**Comment by rusty1s** [comment]
1. The way R-GCN implements this problem is to have a unified `edge_index` representation, where for each edge `edge_type` of shape [E,] holds the relation type. Another way to represent this problem is via 3 graphs, and using bipartite graph algorithms to exchange messages.

2: We have two examples for link prediction, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/autoencoder.py) and [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/link_pred.py).
