### ISSUE TITLE
Questions on mini-batching 

### ISSUE THREAD

**Issue by abasak24** [pyg-team/pytorch_geometric#1474]
## ❓ Questions & Help

Hello, 
I am new to PyG and I am trying to understand the mini-batch description in the documentation in these two links: https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches and https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html.  May I please ask a few questions to clarify my understanding of these documentation examples? 

1) I want to confirm that the presented example is considering the scenario where we are training on multiple graphs, not a single graph. Is that correct? 
2) In the concatenated representations _A_, _X_, and _Y_ , what does _n_ mean? Is it the number of nodes in this batch? If so, the nodes can come from any of the multiple graphs. Is that correct? 
3) In _A_, what are _A1_, _A2_,... _An_? Is each _Ai_, the adjacency matrix of an entire graph? In my understanding, a graph's topology is laid out in a COO tensor format (edge_index). What is the overhead of converting a COO into an adjacency matrix for this mini-batching purpose? 
4) How does mini-batching work when we are dealing with a single graph. What forms do A, X, and Y take then? 

Many thanks for some clarifications on the above questions.

**Comment by rusty1s** [comment]
Hi and thanks for your interest :)

1. That's correct.
2. In this case, `n` stands for the number of graphs/adjacency matrices/examples.
3. `A_i` denotes the adjacency matrix of a single graph. Since all `A_i`s are sparse matrices in COO format, there is no overhead in stacking those sparse tensors diagonally. The resulting matrix is still sparse. I will try to make this more clear in the documentation.
4. There is not yet a unified way to deal with single large-graphs in a mini-batch fashion. PyG provides multiple ways to work on those large graphs, *e.g.*, via [Neighbor Sampling](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.NeighborSampler), [Clustering](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.ClusterLoader), or [random node/edge/random walk sampling](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.GraphSAINTSampler).

**Comment by abasak24** [comment]
Got it, thank you!
