### ISSUE TITLE
Is there any benchmark test for pytorch_geometric version DimeNet?

### ISSUE THREAD

**Issue by Nanco-L** [pyg-team/pytorch_geometric#1500]
## ❓ Questions & Help

Hello.

As I mentioned in the title, is there any benchmark test for pytorch_geometric version DimeNet?

I found that some part of implementation is not match with the original DimeNet paper
(https://arxiv.org/pdf/2003.03123.pdf)

For example,
In original paper (Fig. 1), angular message passing is done in order of k->j->i (k is neighbor of j and j is neighbor of i). Thus, angle of kji is needed, not angle of jik like the code below.
https://github.com/rusty1s/pytorch_geometric/blob/7b2a1ab577cc90fde0f776cbfd8c696d257c1c9a/torch_geometric/nn/models/dimenet.py#L446-L449

In original paper (Eq. 8), first term is not 1./x but 1.
https://github.com/rusty1s/pytorch_geometric/blob/7b2a1ab577cc90fde0f776cbfd8c696d257c1c9a/torch_geometric/nn/models/dimenet.py#L57

In original paper (Eq. 7 and page 5, continuous cutoff paragraph, line 3), radial basis function is `envelop * sqrt(2/c)*(sin(n*pi*d/c))/d`.
https://github.com/rusty1s/pytorch_geometric/blob/7b2a1ab577cc90fde0f776cbfd8c696d257c1c9a/torch_geometric/nn/models/dimenet.py#L75

Of course, I'm not familiar with DimeNet but this differences are weird.
Thus, I wonder that performance of this version of DimeNet is consistent with TF version of DimeNet or the results in original paper. 
If not, I think performance test is required for this version of DimeNet.

**Comment by rusty1s** [comment]
Hi and thank you for this interesting issue. I think most of your concerns are correct. However, for my implementation, I mostly followed the code from the original repository, which might explain those differences:

1. Concerning the angular computation, the author left a comment in his official repository, see https://github.com/klicperajo/dimenet/blob/master/dimenet/model/dimenet.py#L83-L87. We inherit this error here since we do want to make use of the pre-trained models.

2. The envelope is divided by the inputs in the original implementation, see https://github.com/klicperajo/dimenet/blob/master/dimenet/model/layers/envelope.py#L21.

3. The radial basis function is computed exactly the same way as in the original implementation, see https://github.com/klicperajo/dimenet/blob/master/dimenet/model/layers/bessel_basis_layer.py#L28-L29.

IMO, I think the implementation is in-line with the official one. For your specific questions regarding DimeNet, it might be best to contact the author directly.
