### ISSUE TITLE
Can we put dependencies like torch-scatter in the pypi repo?

### ISSUE THREAD

**Issue by pafi-code** [pyg-team/pytorch_geometric#1591]
## ❓ Questions & Help

Currently it is recommended to install the dependencies `torch-scatter`, `torch-sparse`, `torch-cluster`, `torch-spline-conv` via

```
pip install package_name==version+{hardware} -f https://pytorch-geometric.com/whl/torch-version.html
```

If you now develope a package that uses `pytorch-geometrics` you can't install it automatically via `setuptools` in a nice and clean way. At least I don't know of any. You always need to install these extra requirements by hand unfortunately.

1. Do you have an approach on how to automate installing these extra dependencies with the install command above?
2. It seems like the packages are in the official PyPi, why is it recommended to install them like above?

Thanks in advance!

**Comment by rusty1s** [comment]
1. In general, it is hard to automate that since binaries depend on the CUDA version of your system. As an alternative to `setuptools`, you can create a `requirements.txt` file with the following content:
```
-f https://pytorch-geometric.com/whl/torch-version.html
torch-scatter==latest
torch-sparse==latest
...
torch-geometric
```
Alternatively, you can also simply use `pip install torch-...`, but this requires the user to compile the CUDA kernels on its own.

2. The PyPi packages requires installation from source, while the `pip install ... -f ...` installation uses pre-built binaries for all the different CUDA versions.

I'm sorry that there isn't a straightforward way to install this library using `setuptools`, but this is a result of providing different pre-built CUDA versions. The same problem applies to PyTorch, too.
