### ISSUE TITLE
Dilated convolutions (Sorting neighbors by proximity)

### ISSUE THREAD

**Issue by dvirginz** [pyg-team/pytorch_geometric#1592]
## ❓ Questions & Help

The paper DeepGCN offers [dilated convolutions](https://github.com/lightaime/deep_gcns_torch/blob/f95eeb5bf62939e5f62b43eac0842a2db49c735f/gcn_lib/dense/torch_edge.py), which can be very useful for a lot of domains and applications.
PyG offers DeepGCN implementation, but I don't see any recollection of the dilated part.
Can you suggest an easy method of extracting the second/third/etc. neighborhoods excluding the others? (I.e not having the first neighbors in the list returned by `k_hop_graph` for example)

Thanks!

**Comment by rusty1s** [comment]
I think the dilated part is only applied on `knn` graphs, where you sample more than `k` nodes and throw away some.

For general graphs, this is non-trivial though and might not be useful since neighborhood information will explode. An alternative stochastic and more efficient way to achieve that would be to sample random walks with `k` length using `torch_cluster.random_walk` and only use the nodes at length `k` for aggregating.
