### ISSUE TITLE
Hot to embed whole graphs with the (V)GAE?

### ISSUE THREAD

**Issue by THinnerichs** [pyg-team/pytorch_geometric#1606]
## ❓ Questions & Help

Hey there,

I am currently trying to build embeddings for whole graphs given the ARG(V)A / GAE paper and not just nodes/clusters within the graph. Unfortunately, I am struggling to modify the given examples to make it work.

 Any help is appreciated. :)

**Comment by rusty1s** [comment]
Can you give some more details on what you are trying to achieve? How do you want your network architecture to look like?

Given that you are trying to embed whole graphs, you may need a global readout function, and the decoder needs to map this information back to the nodes, *e.g.*:
```python
h_v = encoder(...)
h_g = h_v.mean(dim=0)
h_v = self.mlp(h_g)
```
I'm hot sure though if that works, and there might exist better ideas to tackle this problem :)

**Comment by THinnerichs** [comment]
Its about genealogies of cells, i.e. an ancestry tree for e.g. a stem cell. I want to learn a representation from its overall structure. Some may divide more often earlier, some do so later. I plan to have the division times encoded as the node features (So called Cell Tacking Ontology (CTO)). As each cell is just dividing into 2 successors, the degree itself is between 1 and 3, and thus not very informative. 

As this is unsupervised, I would like to use an autoencoder for this task. 

Not sure whether just averaging over the nodes really "encodes" the structure in representative way. I am quite surprised, that noone else had this issue or something alike up until now. :D

Does the InnerProduct Decoder do the job somehow, regarding the mapping back to the nodes/adjacency matrix?

**Comment by rusty1s** [comment]
I think that this is still an open and challenging problem. There is some work on it already ([GraphVAE](https://arxiv.org/pdf/1802.03480.pdf)), which is mostly consistent with my description above.

I think in general one can expect that readout functions encode global graph properties as long as the node embeddings in the previous layer do. There might be better ways to tackle this, *e.g.*, via clustering/pooling to learn encode more local patterns, but I'm not aware of any work that tries to do this.

In the end, graph autoencoders are also challenging since you need to somehow tackle the problem of reconstructing isomorphic graphs (which should, ideally, also have a reconstruction loss of zero).

**Comment by SasCezar** [comment]
Hi @THinnerichs, I'm also having the same issue, did you found a solution for training a graph level embedding using the autoencoder?

**Comment by THinnerichs** [comment]
Hey @SasCezar, 
sorry for the late reply. Indeed, I tried Matthias' approach and it worked kind of meh. I have to admit that the signal was low and rather sophisticated, and I didn't have that much time. Eventually, it was just a hypothesis to test. I transformed the problem to a root node classification challenge, which worked in my case.

I am currently quite busy, but would love to investigate this further when times ease.
