### ISSUE TITLE
whether SplineCNN is Convolution based or graph based algorithm?

### ISSUE THREAD

**Issue by shangguan9191** [pyg-team/pytorch_geometric#1667]

**Comment by rusty1s** [comment]
Well, it is a message passing operator on graphs. Therefore it can be seen as both convolution based and graph-based (since it aggregates information from neighboring nodes - just like a CNN or other GNNs do). In fact, SplineCNN exactly models the CNN operator on regular domains (feel free to check out the paper for more details on that).
