### ISSUE TITLE
Volume and Surface area estimation

### ISSUE THREAD

**Issue by srivathsan-g** [pyg-team/pytorch_geometric#1853]
Hi,
I have a problem statement where I am given the video of multiple similar (curved) objects moving in a conveyor belt at a constant speed and their volumes and areas need to be estimated. Is it possible to do this using this using this package? If yes, do point me in the right direction and some ideas to start with. Also, will I be required to use multiple views of the same objects for my problem? (It is possible for me to obtain multiple views for my use case)

Thanks in advance.

**Comment by rusty1s** [comment]
I'm not aware of any work that tries to use GNNs to estimate volume and surface area of objects. Do you have some pointers? I'm pretty sure that it can be tackled by GNNs (and therefore with the help of this package), since one can use GNNs to learn about local and global shape features efficiently (similar to how one would use them to do point/object classification/segmentation).

**Comment by samiit** [comment]
Thanks for the great work @rusty1s. I am working with @srivathsan-g on this problem, and we're seeing the feasibility of estimating the surface area of a heap of, say, sand or soil, as well as when it is on a conveyor belt, like shown [here](https://www.exctmach.com/d/pic/belt-conveyor/belt-conveyor/belt-conveyor-sand.jpg). Since both of us are just starting out on GNNs, we weren't sure if this is the best approach. We thought that if we can generate 3d surfaces from 2d images, then surely a regression output would be possible!

**Comment by rusty1s** [comment]
Sure that is possible. I think that‘s a really interesting application. Happy to discuss any questions that May occur.

**Comment by samiit** [comment]
Hi Matthias,

I am watching your nice talk at the [summer school](https://www.youtube.com/watch?v=bgKScUgAyvM) to get started. Could you give some basic direction how we may proceed? Any tutorials, etc., that we can use for drawing inference on multi-view images? We got something from OpenCV using the block-matching algo, but hoped a DL based, especially, GNN based approach would do much better.

Sam

**Comment by rusty1s** [comment]
As far as I understand, you have multiple images from different views, use a CNN backbone to learn on these images in a siamese fashion, and combine those outputs using a GNN to make the final prediction. Is that correct? I think this is very much related to any point cloud / mesh / voxel prediction task from multi-view images, but instead of generating objects you want to predict their properties.

Have you looked at such methods already? A starting point may be [MVPNet](https://arxiv.org/pdf/1811.09410.pdf).
