### ISSUE TITLE
Incrementally adding new samples to the dataloader object

### ISSUE THREAD

**Issue by richardrl** [pyg-team/pytorch_geometric#1855]
What's the most efficient way of doing this?

I guess a naive way would be to to .to_data_list() and .from_data_list() and append to the datalist everytime you want to add new samples. But this seems inefficient.

**Comment by rusty1s** [comment]
I'm not exactly sure what you are trying to do. Do you want to add examples to the dataset that the dataloader should pick up, or do you want to add examples to a given batch?

In case you mean the first, I guess you can just re-instantiate your `DataLoader` with a new dataset (where new samples are added). In case of the latter, I suggest to use `DataListDataloader` in order to remove the `to_data_list` call. You can then add examples and use `from_data_list` only once.
