### ISSUE TITLE
sparse_to_dense

### ISSUE THREAD

**Issue by itzAmirali** [pyg-team/pytorch_geometric#1871]
Hello,

I am using someone's codes from 2019.
In his code, he has interted a sparse_to_dense from geometric.utils function.
But by running it, I get an error now.

I have checked your DOCs, and there is no function there with this name.

I am wondering if the name of this function is changed?

Thanks

**Comment by Amiiirali** [comment]
So I found that the version they have used was 1.2.1.

Now, there is another problem:
RuntimeError: scatter_add() expected at most 5 argument(s) but received 6 argument(s). Declaration: scatter_add(Tensor src, Tensor index, int dim=-1, Tensor? out=None, int? dim_size=None) -> (Tensor)

Any help would be appreciated!

**Comment by rusty1s** [comment]
Sorry for the inconveniences. It's true that some utility functions changed over time. For example, `sparse_to_dense` got replaced by `torch_geometric.utils.to_dense_adj`. In addition, the `torch-scatter` API changed slightly over time. I feel like instead of downgrading PyG (and its external packages), you should try to replace `sparse_to_dense` with `to_dense_adj`.
