### ISSUE TITLE
Node classification on multi graphs

### ISSUE THREAD

**Issue by ZijianWang1995** [pyg-team/pytorch_geometric#1952]
## ❓ Questions & Help

Hi there,

The tutorial of node classification is always to deal with one single graph, like Cora.

My current problem is that I have about 40 Cora-like graphs, and want to classify some nodes in each graph. 
Indeed, **I want 80% of them (32 graphs) to be feed into the model for code-classification training instead of a single graph.** And the last graphs are for test and validation.
 
How can I achieve this function? Do you have any ideas?

Thanks in advance.

**Comment by rusty1s** [comment]
That is similar to the `PPI` dataset, which contains multiple graphs on which you would want to perform node prediction, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/ppi.py).

In general, this can be treated like the CORA example, but instead of simply operating on a single `data` object, you use a `DataLoader` to operate on batches of graphs.

**Comment by ZijianWang1995** [comment]
@rusty1s Thanks very much for your explanation. This is a very good example. It makes me to think about another way.  Does you think the following way is feasible? 
I put many small graphs into a big graph, where I reindex the node number (I assume they have the same length features). Even though in a  big graph, there are no connection between the small graphs.  Then I  feed the big graph into the model for training, validation and test. 

Looking forward to hearing your opinion.

**Comment by rusty1s** [comment]
Yes, that‘s exactly what the data loader is doing already.

**Comment by ZijianWang1995** [comment]
Got that! Very helpful!!! And the code is so concise and clear to read. 
Thank you Matthias. And happy new year!
