### ISSUE TITLE
some confusion about mini-batch

### ISSUE THREAD

**Issue by caoxu915683474** [pyg-team/pytorch_geometric#2165]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

I have some questions about mini-batch training.

My task is graph level classification. The problem is that when I use batch training, the graphs in a batch merge into a big graph.  For example, in batch we have graph 1 which contains nodes[a, b, c, d] edges [[a, b], [b, d], [a, d]] and graph 2 contains [a, b, e, f] edges [[a, e],[b, f],[e, f]].   In mini-batch, the big graph will be nodes [a, b, c, d, e, f], and as they all contains nodes [a, b]. when training, graph1 will have a look at graph2 nodes [e, f]. When testing, if we set batch size 1 the   mode will see nothing from other graphs. but when testing we set 100, the predict of each graph is influenced by other graphs if they have same nodes. So different batch size for test will have different results.

**Comment by rusty1s** [comment]
Note that message passing GNNs are not influenced by that, since no messages are exchanged between nodes of different graphs. However, for readout functions, batch information is critical to achieve independence of batch size. We achieve that by the `data.batch` vector and our custom readout functions, such as `global_mean_pool`. You can find an example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mutag_gin.py).
