### ISSUE TITLE
RandomLinkSplit' object has no attribute 'num_features'

### ISSUE THREAD

**Issue by kaoumrf** [pyg-team/pytorch_geometric#3183]
## ❓ Questions & Help

I created my heterograph following steps from LOADING GRAPHS FROM CSV  and now I'm trying to split the data
`data.train_mask = data.val_mask = data.test_mask = None`
`data = T.RandomLinkSplit(data)`

In the last version of PyG, train_test_split_edges is returning that its deprecated. So I used instead RandomLinkSplit and when I execute this line:
`encoder = VEncoder(data.num_features, out_channels=latent_size)`

It returns:
`AttributeError: 'RandomLinkSplit' object has no attribute 'num_features'
`

What's the equivalent of num_features ? I couldn't find anything about this in the docs

**Comment by rusty1s** [comment]
The `RandomLInkSplit` transform behaves a little bit different, as it will return three data objects:
```python
train_data, val_data, test_data = T.RandomLinkSplit(data)
```
Here, `*_data.edge_index` denotes the graph structure used for message passing, while `*_data.edge_label_index` and `*_data.edge_label` denote the training/evaluation edges and their corresponding labels. You can find an updated example of using `RandomLinkSplit` [here](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/link_pred.py), and it only requires a few modifications to convert your script from `train_test_split_edges` to `RandomLinkSplit`.

**Comment by anniekmyatt** [comment]
I have a question on the RandomLinkSplit changes in the pull request that is linked here so I hope it's ok if I ask here:
is the intention of the usage for a heterogeneous graph that I run `RandomLinkSplit` several times, with different inputs for `edge_type` and `rev_edge_type` to get a train/val/test split for my different edge types?

**Comment by rusty1s** [comment]
The `RandomLinkSplit` only splits a the links of a single edge type, which IMO models the standard use-case in which we want to predict certain links, e.g., for recommendation, between two different node types, e.g.,users and products. What is a typical example of link prediction across multiple node/edge types?

**Comment by anniekmyatt** [comment]
Thank you for explaining your rationale!

My use case is adverse event prediction in the way described by [Zitnik](https://academic.oup.com/bioinformatics/article/34/13/i457/5045770)  et al. I've currently got an implementation that works well with pytorch-geometric 1.8.0, deepsnap (which does the link splitting) and some custom code to handle the minibatch sampling. I was just curious about the new PyG 2.0 release with the heterogeneous graph support, so I started implementing things using that and hit this question.

I can imagine any use case where different link types have some underlying commonalities, so where the kind of decagon decoder described in the Zitnik paper could be used, would benefit from having different edge types included in the training loop. One other practical example I can think of is if you try to identify errors in utility network asset data, where different edges could represent links between assets of different but related properties.

**Comment by rusty1s** [comment]
That's interesting. I think we can allow `RandomLinkSplit` to take a list of edge types (or `None`) as input as well to allow splitting across different edge types. I'm not yet sure how to prevent data leakage in case `edge_type` is `None` (=split across all edge types) though. Any idea? Do you know how this is handled in DeepSNAP?

Supporting a list of edge types should be straightforward though. Let me know if this is something that might benefit you, and we can quickly integrate it.

**Comment by anniekmyatt** [comment]
Hi, and apologies for the slow reply! I got distracted with life things. 

Tbh, I would like to move towards fully using pytorch-geometric (rather than also have a dependency on deepsnap) but I can also stick with what I've got, especially if you think my use case may be a bit too niche. If it were possible to pass in a list of edges and associated reverse edges, I'd definitely use that feature but it is not urgent for me right now.

Yes, you are right that when the user provides `None`, you wouldn't know which edges are the reverse edges to avoid the target leakage with. Deepsnap doesn't handle this either and you do end up with target leakage, in my case for about 16% of the validation and test edges. You can very easily see this is happening in their [link prediction collab notebook](https://colab.research.google.com/drive/1ycdlJuse7l2De7wi51lFd_nCuaWgVABc?usp=sharing) where the edges are coloured by the split type they belong to(train/val/test), shown for the homogeneous case and the same is true for the heterogeneous case.

So in my case I have done two things, one is a postprocessing step to remove clashing edges from the training edges, and another is to have my own version of a splitter, but it is frankly slow and not pretty, so I'm not so keen on using it.

One thing that deepsnap does quite nicely is to separate message passing edges from supervision edges, and then split those supervision edges in train/val/test, although you can also end up with message passing edges in one direction and a supervision edge in the return direction. This "feels" a bit problematic or "untidy" but I haven't had time yet to investigate the impact of this more systematically, and maybe it's fine.. 

How would pytorch-geometric support this functionality of separating the message passing and supervision edges? In deepsnap it works through setting the `edge_train_mode="disjoint"` flag when constructing a `GraphDataset` object.  Is this something you feel your other users would benefit from as well?

**Comment by rusty1s** [comment]
Yes, I think a "disjoint" train mode makes sense as well. Let me try to implement something like that.

**Comment by rusty1s** [comment]
I made a PR that allows to sample links across multiple edge types, see https://github.com/pyg-team/pytorch_geometric/pull/3268. Can you see if that fits your needs?

Furthermore, I like the idea of "disjoint" training, and would like to integrate it as well. However, I don't see where DeepSNAP allows to customize the number of supervision edges (am I missing something)?

**Comment by anniekmyatt** [comment]
Yes, this PR looks like it will do the trick :-) Thank you! 

Just to clarify the way the `disjoint_train_ratio` works here, let's assume there are 100 edges in the graph, and we set 
```
num_val=0.1
num_test=0.1
disjoint_train_ratio = 0.2
```
This will result in 80  training edges, of which 20%, so 16,  are supervision edges, and 64 are message passing edges.
We also get 10 validation and 10 test edges. And this would apply for each edge type.
Is this right?

**Comment by rusty1s** [comment]
This is correct. I think this is similar to how DeepSNAP determines the train ratio of message passing edges and supervision edges. Let me know if this is the correct behavior in your opinion :)

**Comment by anniekmyatt** [comment]
Yes, you're right, it is just like the behavior in deepsnap (I just double checked). I think your interface is a bit clearer, because in deepsnap you first call 
```
dataset = GraphDataset([dg], task=task, edge_message_ratio=0.8 , edge_train_mode="disjoint")
``` 
and then 
```
dataset_train, dataset_val, dataset_test = dataset.split(transductive=False, split_ratio=[0.8, 0.1, 0.1])
```
which could suggest to an unsuspecting user that 80% of edges are reserved for message passing, and 20% are supervision edges, and then you split those supervision edges using the [0.8, 0.1, 0.1] split ratio, yielding something like
80 message passing edges, 16 training supervision edges, 2 validation and 2 test edges. But this is not the case, the behaviour is as you implemented here.

I think the fact that you have it all handled in one function doesn't give any counter-intuitive pointers like this. 

Thanks again! :)
