### ISSUE TITLE
Slow Loading of Docs website

### ISSUE THREAD

**Issue by ParasKoundal** [pyg-team/pytorch_geometric#3809]
## 📚 Documentation
Hi,
I work with PyG almost on a daily basis and really love it. However, https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html is awfully slow to load. I have tried it on multiple browsers and with different connection types (wifi, lan). 

It seems the issue is on the backend. Any plans to resolve this.

**Comment by rusty1s** [comment]
Hi and sorry for the late reply.

How slow is it to load for you? For me, the website loads quite fast, but the actual rendering takes a bit of time (~1-2 seconds). This is probably due to the math formulas which get rendered on the fly. In addition, `torch_geometric.nn` has become quite large over time.

One way to fix this would be to separate `torch_geometric.nn` subpackages (e.g., `conv`, `pool`, ...) into their own dedicated site.

**Comment by jasperhyp** [comment]
It's quite fast for me though. Specs: US, WiFi within an education institute.

**Comment by ParasKoundal** [comment]
The text loads maybe within a second. The formulas maybe in next 2/4 seconds. However, if I want to Ctrl+F in first 10/15 secs it slows down in loading as well as the search is slow

**Comment by rusty1s** [comment]
This should be finally resolved with https://github.com/pyg-team/pytorch_geometric/pull/6744.
