### ISSUE TITLE
Adjustment of the decoding operation in the Graph U-Net model.

### ISSUE THREAD

**Issue by Gerrit28282** [pyg-team/pytorch_geometric#3962]
### 🛠 Proposed Refactor

Referring to https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/models/graph_unet.py:

I believe in line 106 the new `x`-value should not be created from the sum of `up` and `res` but rather just `up`. `res` in that case are the saved x-values from the encoding part in the same layer. 
By just saving the values from the encoding and using them again during decoding , the network is enforced to learn to do nothing as it can recreate its input by just loading the saved values. 
I believe this is not intended and I also can't find reasons for this in the corresponding Graph U-Net paper. Here, just the storing of spacial information is documented. During decoding, the feature matrix for the new graph is created containing just zeros. The rows at the saved indices are then updated while the other ones remain zero. The subsequent GCN-operation then makes predictions on the missing nodal values. The initial emptiness after unpooling is also visualized in figure two and three in the Graph U-Net paper. 

### Suggest a potential alternative/fix

During decoding, use the `res` variable just for information about the graph structure for the new layer, i.e. number of nodes and hidden layer.

**Comment by rusty1s** [comment]
Please correct me if I am work, but I think this is still correct. This part models the skip-connections of a classical U-Net, either via summation or concatenation. If you drop the `res` part here, the model will lose out on all fine-grained information. The paper states:

> We use addition operation in skip connections between blocks of encoder and decoder parts.

**Comment by j-adamczyk** [comment]
@Gerrit28282 they actually are initialized as zeroes, there is just no need to do this explicitly. Remember that "For blocks in the same level, encoder block uses skip connection to fuse the low-level spatial features from the encoder block". So we first initialize the removed nodes as zeros, and then we have to fill them with a skip connection, which is a summation in paper. So you get `0 + res = res` for any node that was removed, so just `res`. For nodes that were not removed you get $res + up$.

Also this is not true: "By just saving the values from the encoding and using them again during decoding , the network is enforced to learn to do nothing as it can recreate its input by just loading the saved values.". By this logic, any ResNet CNNs would not work at all, since they can propagate the original input all the way. Also U-nets for image segmentation would not work. For U-nets this will work, since you get different representations from skip connection and from upsampled data, and summing them results in new node features. Also note that you get gradients going both downwards and through skip connections to learn all of this.

**Comment by rusty1s** [comment]
Thanks for chiming in. I think it is safe to close this issue, please re-open if you strongly feel otherwise.
