### ISSUE TITLE
Global Pooling via `EquilibriumAggregation`

### ISSUE THREAD

**Issue by rusty1s** [pyg-team/pytorch_geometric#4447]
### 🚀 The feature, motivation and pitch

Support the recently proposed "Equilibrium Aggregation" scheme which defines an implicitly given global readout function. The [blog post](https://fabianfuchsml.github.io/equilibriumaggregation/) goes over it in detail.

* [Paper](https://arxiv.org/abs/2202.12795): The code is given in the appendix.

**Comment by Padarn** [comment]
This paper is pretty cool. I'm happy to start on this.

I wonder if its worth also trying to implement it as a possible aggregation function in message passing, rather than just as a global readout. That way the global readout version could be implemented just by passing a different adjacency matrix to the layer?

**Comment by rusty1s** [comment]
I think providing it as a global readout layer is sufficient for now. I don‘t think we need to add it as a general option for aggregation in any message passing layer for now.

**Comment by Padarn** [comment]
Fair enough, worth doing separately

**Comment by Padarn** [comment]
Have opened a PR, and assigned this to myself - still a number of open questions to discuss and a lot of cleaning to do.
