### ISSUE TITLE
Custom aggregation function

### ISSUE THREAD

**Issue by krrish94** [pyg-team/pytorch_geometric#554]
## ❓ Questions & Help

Is it theoretically possible to define custom aggregation functions, as opposed to the available `mean`, `sum`, `max` aggregations? If yes, how do I go about doing this?

I find that the `MessagePassing` module (likely the `scatter` op you use in there) imposes this limitation. Any workaround? Eg. It'll be cool if I could plug in a custom function into the `aggr` argument, and it gets used.

**Comment by rusty1s** [comment]
This is correct and there is currently no workaround to this via the `MessagePassing` interface. Technically, we can also make use of `scatter_mul`, `scatter_div` or `scatter_std`, but I doubt their use-cases in Graph Neural Networks. 

The way to go to implement custom functions is the *degree bucketing* approach. In this approach, you group nodes with equal node degree to form a list of `[num_nodes, num_neighbors, node_features]` tensors. One can then apply custom reduction functions over dimension 1 for each tensor in the list. This is certainly a good general framework to model custom functions, but it comes with the disadvantage of slow runtimes due to the sequential processing of the various node degrees and the poor GPU utilization. We might integrate something like this in PyG to allow any kind of aggregation function though (like the usage of LSTMs). As you said, we could default to it when using custom functions in the `aggr` argument.

**Comment by krrish94** [comment]
One other workaround I can think of is to modify the semantics of the `update()` method, to include aggregation therein. Instead of passing in the aggregated message as an argument, we could pass a concatenation of messages from the neighbouring nodes/edges. As I see, the `update()` method is not parallelized by using `scatter_{}`, so this might gel along smoothly (albeit result in poorer runtime).

**Comment by rusty1s** [comment]
Please see https://github.com/pyg-team/pytorch_geometric/pull/4379 for an example.
