### ISSUE TITLE
Unnecessarily large memory usage in `from_networkx()`

### ISSUE THREAD

**Issue by pi314ever** [pyg-team/pytorch_geometric#6964]
### 🐛 Describe the bug

[`from_networkx()`](https://github.com/pyg-team/pytorch_geometric/blob/209268a4e48c9c9f701f02f98520d5b96c53468e/torch_geometric/utils/convert.py#L169) appears to copy the data for `edge_index` and `x` multiple times throughout the creation of the Data object. For large graphs, this results in a high likelihood of OOM errors. 

In particular, here are the places `edge_index` is copied:
- lines 209-214 makes 2 copies
- line 239 makes a fragmented copy (using python `int` objects)
- line 278 creates another copy since `torch.cat` copies the data

And here are the places `x` is copied:
- line 232 makes a fragmented copy (using python `int` objects)
- line 266 creates another copy since `torch.cat` copies the data

In total, there are 5 copies of `edge_index` and 3 copies of `x` (including the original) from what I can tell, and more copies of other data as well. 

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.13.1
* OS: Arch Linux
* Python version: 3.7.1
* CUDA/cuDNN version: 12.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): `pip install ...` for cu117
* Any other relevant information (*e.g.*, version of `torch-scatter`): 
```
torch-scatter==2.1.0+pt113cu117
torch-sparse==0.6.16+pt113cu117
torch-spline-conv==1.2.1+pt113cu117
networkx==2.6.3
```

**Comment by rusty1s** [comment]
Thanks for this issue. You are right that we are indeed copying here multiple times. The only way to optimize this would be to directly write edges into a `torch.Tensor` rather than first converting to a list and then using `torch.tensor()` on top, but IMO this feels like a negligible optimization since the data is freed afterwards anyway.

If you have interest in making this more memory-friendly, I welcome a PR though :)

**Comment by rusty1s** [comment]
Done via https://github.com/pyg-team/pytorch_geometric/pull/7119.
