### ISSUE TITLE
IndexError when using dimnet plus plus with pretrained on qm9 dataset (just running the example provided by PYG)

### ISSUE THREAD

**Issue by AmgadAbdallah** [pyg-team/pytorch_geometric#7099]
### 🐛 Describe the bug

I was trying to run the example provided by PYG using dimnet plus plus pretrained on qm9 dataset, the lik for the example: https://github.com/pyg-team/pytorch_geometric/blob/master/examples/qm9_pretrained_dimenet.py

I didn't change anything in the code, yet it gave me this error:
IndexError: Only slices (':'), list, tuples, torch.tensor and np.ndarray of dtype long or bool are valid indices (got 'Tensor')

### Environment

* PyG version: 2.3.0
* PyTorch version: 2.0.0+cpu
* OS: Windows-10-10.0.19045-SP0
* Python version: 3.10
* CUDA/cuDNN version: N/A
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for reporting. @wsad1 do you mind to take a look?

**Comment by EdisonLeeeee** [comment]
@rusty1s @AmgadAbdallah This is because `perm` is a `torch.int32` Tensor but only `torch.int64` is supported for `torch_geometric.data.Dataset`. A quick fix is to convert `perm` to `torch.int64` Tensor.

https://github.com/pyg-team/pytorch_geometric/blob/3c1501833b13cb87e110a89edef5aa6ee164c190/torch_geometric/nn/models/dimenet.py#L633

**Comment by AmgadAbdallah** [comment]
Thank you very much!
