### ISSUE TITLE
Doubt in normalize_scale

### ISSUE THREAD

**Issue by dhorka** [pyg-team/pytorch_geometric#736]
Hi,

I have a doubt related to the function normalize_scale. When you are calculating the scale: 
 scale = (1 / data.pos.abs().max()) * 0.999999

Why are you multiplying the obtained value to 0.99999. I suppose is for any kind of numerical stability, but I am not able to see which trouble I will have if I avoid this multiplication. I mean, Which problem are you trying to avoid?

Thanks,

**Comment by rusty1s** [comment]
I actually wanted to enforce (-1,1) ranges instead of [-1, -1] ranges. The reason for this has a bit of history and can be contributed to the `voxel_grid` pooling, which pools points inside an interval `x_start <= x < x_end`. The applied normalization therefore ensures that points on the boundary do not get assigned to a unique voxel.
