### ISSUE TITLE
Subgraph sampling from larger graphs.

### ISSUE THREAD

**Issue by SaschaStenger** [pyg-team/pytorch_geometric#788]
## ❓ Questions & Help

Hi, i'm currently trying to produce smaller sub-graphs out of really large graphs in my dataset and have a few questions regarding this. 

`NeighborSampler` is the method, that i'm using and when reading the documentation, I do believe, that `__produce_subgraph__(b_id)` should be the method that returns me a data object to save. But i can't figure out, what b_id stands for. 
My code for testing this is as follows
`loader = NeighborSampler(data, size=[10, 25], num_hops=2, batch_size=1,
                         shuffle=True, add_self_loops=True)
batch_1 = loader.__get_batches__()[0]
print(loader.__produce_subgraph__(batch_1))`

The original data object has the following attributes
`Data(edge_attr=[469], edge_index=[2, 469], x=[323, 747], y=[1])`
But this only returns me
`Data(b_id=[1], e_id=[2], edge_index=[2, 2], n_id=[3], sub_b_id=[1])`
Which is much smaller, then i specified  in the Sampler. My guess is, that i'm doing something wrong with the b_id.

**Comment by rusty1s** [comment]
`b_id` holds a one-dimensional tensor of node indices to produce subgraphs for and `e_id` and `n_id` hold the indices that got samples from the original graph for edges and nodes respectively. Since you are having a batch size of 1, `b_id` should be of size 1. And it seems that this node does only have one neighbor which also has only neighbor, resulting in 3 sampled nodes.
