### ISSUE TITLE
WikipediaNetwork, Squirrel and potentially others not correct

### ISSUE THREAD

**Issue by yCobanoglu** [pyg-team/pytorch_geometric#8086]
WikipediaNetwork not correctly working for Squirrel Dataset and potentially Chameleon and Crocodile.

First the `data["test_mask"]` have wrong dimensions for Squirrel so: `test_mask` is not a vector, but a matrix. Secondly the `data.y` is long ? Meaning not suitable for regression as it probably has classes as longs not floats. 
There is a fix: https://github.com/niuzehao/gnn-gp/blob/master/src/datasets.py 
The fix is the class `class WikipediaNetwork(InMemoryDataset)`in the file above.

### Environment

* PyG version: 2.3.1

**Comment by rusty1s** [comment]
I don't see an issue with this TBH. The dataset is cast into a classification task: "We classify the nodes into five categories in term of the number of the average monthly traffic of the web page." Regarding `test_mask`, it is correct that there exists multiple masks since the dataset provides multiple splits to evaluate against. If you just wanna operate on a single split, you can do `test_mask[:, 0]`.

**Comment by yCobanoglu** [comment]
ok but there is a parameter for WikipediaNetwork:  `geom_gcn_preprocess` which will turn the Dataset into a classification task.  The default value is False and the Squirrel Dataset is long anyway ? That is not correct right?
Optionally: Would be good to mention in the docs that the the test mask has multiple splits. I could imagine that could become a problem for PyGym because one generally expects a vector there not a matrix with multiple splits.

**Comment by rusty1s** [comment]
Note that `geom_gcn_preprocess` is set to `True` by default. I added a note on the shape of masks to the doc, see https://github.com/pyg-team/pytorch_geometric/pull/8107.

**Comment by yCobanoglu** [comment]
ok thanks !

**Comment by yCobanoglu** [comment]
@rusty1s One last thing why are the test masks not available for the Classification ?
