### ISSUE TITLE
LSTM in Set2Set computation question.

### ISSUE THREAD

**Issue by RuihongQiu** [pyg-team/pytorch_geometric#827]
## ❓ Questions & Help

Hi,

May I ask how is the [first step](https://github.com/rusty1s/pytorch_geometric/blob/62bf0f3a3cb3a86b8c5ba2f1c30da3d8874dff6b/torch_geometric/nn/glob/set2set.py#L57) in the first loop of the computation of the Set2Set?
```python
h = (x.new_zeros((self.num_layers, batch_size, self.in_channels)),
             x.new_zeros((self.num_layers, batch_size, self.in_channels)))
q_star = x.new_zeros(batch_size, self.out_channels)

for i in range(self.processing_steps):
    q, h = self.lstm(q_star.unsqueeze(0), h)
    ......
```

Both inputs of the LSTM are initialized as 0 vectors here. Are the updated `q` and `h` only related to the bias of the parameters in LSTM units?

**Comment by rusty1s** [comment]
That's a great question. Indeed, the first iteration of computing `q` can only make use of the bias parameter. Since there is no official code available, it is up to the user how to initialize `h` and `q_star`. I borrowed this initialization scheme from [here](https://github.com/RexYing/diffpool/blob/master/set2set.py).

**Comment by RuihongQiu** [comment]
Thank you and I will discuss it with Rex there.
Cheers!
