### ISSUE TITLE
[Question] effect of `contiguous()` function on graph data constructor

### ISSUE THREAD

**Issue by pavaris-pm** [pyg-team/pytorch_geometric#8735]
### 📚 Describe the documentation issue

I saw PyG documentation that we have an alternative way to define a graph object in torch geometry by `transpose` and call `contiguous` on it before passing them to the data constructor to reduce confusion for someone trying to make it compatible to COO format, with that, i have some question with the usage of `contiguous()` in this case:

Here is the suggested code in the documentation
```python
import torch
from torch_geometric.data import Data

# with contiguous
edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index.t().contiguous())
>>> Data(edge_index=[2, 4], x=[3, 1])
```

However, if we transpose the defined edge index tensor only without needed from `contiguous()`, we still get same result from the Data object same as what we do with contiguous

```python
# without contiguous (transpose the tensor only)
data = Data(x=x, edge_index=edge_index.t())
>>> Data(edge_index=[2, 4], x=[3, 1])
```

According to that, i just want to ask that why we need to add `contiguous()` here in order to create a graph object. Are there any difference between adding or removing it out from this given code ? what will happen in the background after we made it ?

**Comment by rusty1s** [comment]
Many of the PyG operations assume that `edge_index[0]` (the source indices) and `edge_index[1]` (the destination indices) are contiguous in memory for maximum efficiency. Some internal kernels, such as `torch_scatter` or `pyg-lib` also require contiguous memory access and error out otherwise. As such, it is good to ensure that `edge_index` is indeed contiguous, although 95% of the PyG codebase will still work but will be less efficient.

**Comment by pavaris-pm** [comment]
That's a very quick reply! Thanks for your explanation. It's very helpful 👍🏻
