### ISSUE TITLE
Questions about labels in PPI datasets

### ISSUE THREAD

**Issue by tiancanzhilei** [pyg-team/pytorch_geometric#890]
## ❓ Questions & Help
I want to know if the labels of the PPI data are multi-label. If so, why is dataset.num_classes = 121?

**Comment by rusty1s** [comment]
Yes, it is a multilabel dataset where each node belongs to multiple classes within 121 classes.

**Comment by RemyLau** [comment]
Does ``graphgym`` have loss function for dealing with multilabel datasets like PPI?
Looking at ``loss.py``, it seems like currently multilabel classification is not supported.
Will this be updated soon?

https://github.com/pyg-team/pytorch_geometric/blob/d8b8e017c9cd9667b9c3b84a58e65130d54cf50e/torch_geometric/graphgym/loss.py#L37-L45

**Comment by RemyLau** [comment]
Thanks for the quick response @rusty1s . I've tried to test it on the [``GemsecDeezer``](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#torch_geometric.datasets.GemsecDeezer) dataset from Pytorch Geometric, but here's the error I got:

```txt
Traceback (most recent call last):
  File "/mnt/ufs18/rs-027/compbio/krishnanlab/tmp/remy_tmp_test/GTaxoGym/main.py", line 66, in <module>
    train(loggers, loaders, model, optimizer, scheduler)
  File "/mnt/home/liurenmi/software/anaconda3/envs/gtaxogym/lib/python3.9/site-packages/torch_geometric/graphgym/train.py", line 71, in train
    train_epoch(loggers[0], loaders[0], model, optimizer, scheduler)
  File "/mnt/home/liurenmi/software/anaconda3/envs/gtaxogym/lib/python3.9/site-packages/torch_geometric/graphgym/train.py", line 20, in train_epoch
    loss, pred_score = compute_loss(pred, true)
  File "/mnt/home/liurenmi/software/anaconda3/envs/gtaxogym/lib/python3.9/site-packages/torch_geometric/graphgym/loss.py", line 45, in compute_loss
    return bce_loss(pred, true), torch.sigmoid(pred)
  File "/mnt/home/liurenmi/software/anaconda3/envs/gtaxogym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/home/liurenmi/software/anaconda3/envs/gtaxogym/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 713, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "/mnt/home/liurenmi/software/anaconda3/envs/gtaxogym/lib/python3.9/site-packages/torch/nn/functional.py", line 2958, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([2807112])) must be the same as input size (torch.Size([33418]))
```
After some digging, the problem seems to be the lack of support for multilabel classification tasks in general.

First, the output dimension is incorrectly set for the case of multilabel classification. In particular, the output dimension is determined as the number of unique label indices. So in the case of multilabel classification, ``dim_out`` will be set to 2, hence incorrectly identified as binary classification.
https://github.com/pyg-team/pytorch_geometric/blob/d8b8e017c9cd9667b9c3b84a58e65130d54cf50e/torch_geometric/graphgym/loader.py#L195-L196

Second, the evaluation function call in ``logger.py`` does not support multilabel classification. The only supported cases are binary/multiclass classification and regression. Note that ``classification_multi`` is not compatible with the multilabel classification setting, due to the ``_get_pred_int`` call.
https://github.com/pyg-team/pytorch_geometric/blob/d8b8e017c9cd9667b9c3b84a58e65130d54cf50e/torch_geometric/graphgym/logger.py#L98-L124

Finally, as a minor note, the ``split_mode`` currently does nothing and ``split_mode = 'random'`` does not prepare random splits. We have taken care of that by implementing a custom loader module that's hooked to the main GraphGym pipeline. However, the issues mentioned here do not have a clean workaround without overwriting some 'none customizable' source code of GraphGym. We're going to overwrite some of the source code in our own fork to enable support for multilabel classification. If you think this is a valuable extension to be made to the main PyG GraphGym repo, we'll submit a pull request to help with that! Let us know!

**Comment by JiaxuanYou** [comment]
Yes exactly. If you have a more sophisticated use case, you could customize it as well.
